# Site settings
title: Introduction to Humanities Programming
description: "An introduction to Humanities Programming course materials for the Humanities Intensive Learning and Teaching (HILT) program."
baseurl: ""
url: "https://waynegraham.github.io/intro-to-dh-programming"


# build settings
markdown: kramdown
pygments: true
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed

